# Generated by Django 4.2.2 on 2023-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='test', max_length=124, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Text to display', verbose_name='Title'),
        ),
    ]
